### ISSUE TITLE
Scenarios (Example)

### ISSUE THREAD

**Issue by MariaDarkSM** [thejcedeno/monad-uhc#2]
- [ ] #4
 - [ ] #5
 - [ ] #6

**Comment by thejcedeno** [comment]
need to figure out incendo/cloud annotation framework setup. See [wiki](https://github.com/Incendo/cloud/blob/master/docs/README.adoc#annotations)

**Comment by thejcedeno** [comment]
Added example of how it works here: https://github.com/thejcedeno/monad-uhc/pull/9#issue-1650964874

Also see https://github.com/thejcedeno/monad-uhc/blob/main/bukkit/src/main/java/us/jcedeno/anmelden/bukkit/scenarios/ScenarioManager.java#L22-L26 for examples on how to register the scenario. 

Just need to add it to that map :).

**Comment by thejcedeno** [comment]
@MariaDarkSM

**Comment by thejcedeno** [comment]
Notes:

The current implementation is buggy, but it's stable enough for other devs to start writing "Listener" scenarios. Will fix all the bugs when I catch some 💤.
